version: "3"
services:
  echo-service:
    image: hiroki11hanada/wasm-dapr-echo
    build:
      context: .
      dockerfile: echo.Dockerfile
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    ports:
      - "9004:9004"
    networks:
      - hello-dapr
  echo-dapr:
    image: "daprio/daprd:edge"
    ports:
      - "3502:3502"
    command: 
      - "./daprd"
      - "-app-id"
      - "echo-service" 
      - "-app-port"
      - "9004"
      - "-dapr-http-port"
      - "3502"
      - "-placement-host-address"
      - "placement:50006"
      - "-resources-path" 
      - "/components"
      - "-log-level"
      - "debug"
      # - "-dapr-public-port"
      # - "3502"
    volumes:
        - "./config/:/components"
    depends_on:
      - echo-service
      - redis
    networks:
      - hello-dapr
    # network_mode: "service:echo-service"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - hello-dapr

  tests-service:
    image: hiroki11hanada/wasm-dapr-tests
    build:
      context: .
      dockerfile: tests.Dockerfile
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    networks:
      - hello-dapr
  tests-dapr:
    image: "daprio/daprd:edge"
    ports:
      - "3501:3502"
    command: 
      - "./daprd"
      - "-app-id"
      - "tests-service" 
      - "-dapr-http-port"
      - "3502"
      - "-placement-host-address"
      - "placement:50006"
      - "-resources-path" 
      - "/components"
      - "-log-level"
      - "debug"
      # - "-dapr-public-port"
      # - "3502"
    volumes:
        - "./config/:/components"
    depends_on:
      - tests-service
      - redis
    networks:
      - hello-dapr
    # network_mode: "service:tests-service"

networks:
    hello-dapr:
      driver: bridge
      name: hello-dapr
